racenight/racenight/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="frontpage"),
    path('admin/', admin.site.urls),
    path('home/', views.home, name="home"),
    path('myaccount/', views.maindashboard, name="maindashboard"),
    path('bethistory/', views.betHistory, name="bethistory"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('races/', include("races.urls", namespace="races")),
]

racenight/races/urls.py
from django.urls import path
from . import views

app_name = 'races'

urlpatterns = [
    path('dashboard/<int:pk>',views.dashboard, name='dashboard'),
    path('bet/create/<int:pk>', views.createBet, name="bet-create"),  
    path('bet/delete/<int:pk>/',views.deleteBet, name='bet-delete'),   
    path('leaderboard/',views.Leaderboard, name='leaderboard'),
    path('watchrace/<int:pk>/',views.WatchRace, name='watchrace'), 
    path('nextrace',views.WatchNextRace, name='watchnextrace'),       
]

racenight/races/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from django.urls import reverse
from django.db.models.signals import post_save, pre_save, pre_delete, post_delete
from django.dispatch import receiver

from .utils import distributeWinnings

class Race(models.Model):
    STATUS = (
        ('Upcoming', 'Upcoming'),
        ('In Play', 'In Play'),
        ('No More Bets', 'No More Bets'),
        ('Finished', 'Finished')
        )

    number = models.PositiveIntegerField()
    name = models.CharField(max_length=100)
    srcyoutube = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__(self):
        return self.name


class Horse(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name


class RaceEntry(models.Model):
    race = models.ForeignKey('Race', on_delete=models.CASCADE)
    number = models.PositiveIntegerField(default=0)
    horse = models.OneToOneField('Horse', on_delete=models.CASCADE)
    won = models.BooleanField(default=False) 

    def __str__(self):
        return str(self.race) + ' ' + str(self.number) 


class Bet(models.Model):
    raceentry = models.ForeignKey('RaceEntry', on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    winnings = models.PositiveIntegerField(default=0, blank=True)

    def get_absolute_url(self):
        # After update return to race dashboard
        return reverse('races:dashboard', kwargs={'pk': self.raceentry.race.id})
    
    def __str__(self):
        return str(self.raceentry)


@receiver(post_save, sender=Race)
def update_cash(sender, instance, **kwargs):
    print(f'SIGNAL: Race post_save on race {instance.id}')
    if instance.status == 'Finished':
        distributeWinnings(Bet, RaceEntry, instance.id)
   

# @receiver(post_save, sender=Bet)
# def update_bet(sender, instance, **kwargs):
#     print('SIGNAL: Bet post_save' )  
#     print(instance)
#     print(instance.amount)
 

# @receiver(pre_save, sender=Bet)
# def update_bet_pre_save(sender, instance, **kwargs):
#     print('SIGNAL: Bet pre-save')

racenight/races/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib import messages
from django.core import validators

from races.models import Bet

class BetCreateForm(ModelForm):
    # amount = forms.IntegerField(label='',widget=forms.TextInput(attrs={'placeholder':'Stake amount'}))

    class Meta:
        model = Bet
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
            'raceentry': forms.HiddenInput(),
        }
    
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if not (amount>0):
            raise forms.ValidationError('Stake must be greater than zero',
                                        code='InvalidAmount')
        return amount

    def clean(self):
        # Check that a bet has not already been placed on this entry
        # overriding the clean method because we need access to the to the other fields, namely user 
        raceentry = self.cleaned_data['raceentry']
        user = self.cleaned_data.get('user')
        bets = Bet.objects.filter(user=user)
        for bet in bets:
            if raceentry == bet.raceentry:
                raise forms.ValidationError('You have already bet on this horse',
                                            code='InvalidSelection')

        # This error only happens if user had opened the create bet form and tries to place a bet if the race is no longer in-play
        if (raceentry.race.status != 'In Play'):
            raise forms.ValidationError('Sorry - no more bets!',
                                        code='InvalidSelection')
        return self.cleaned_data

class BetUpdateForm(ModelForm):
    class Meta:
        model = Bet
        fields = ['user','raceentry','amount']
        widgets = {
            'user': forms.HiddenInput(),
            'raceentry': forms.HiddenInput(),
        }
    
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if not (amount>0):
            raise forms.ValidationError('Stake must be greater than zero',
                                        code='InvalidAmount')
        return amount

racenight/races/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from races.models import Bet, RaceEntry, Race
from races.forms import BetCreateForm, BetUpdateForm
from django.contrib.auth.decorators import login_required
from braces.views import SelectRelatedMixin
from django.http import Http404
from django.urls import reverse_lazy
from accounts.models import Profile
from django.views.decorators.cache import cache_control
from django.db.models import Sum
from django.contrib.auth import get_user_model
from decimal import Decimal

User = get_user_model()

@login_required
def dashboard(request, pk):
    raceentrys = RaceEntry.objects.filter(race=pk).order_by('number')
 
    bets = Bet.objects.filter(user=request.user, raceentry__race=pk)
    race = Race.objects.get(pk=pk)
    status = race.status

    betstotal = Bet.objects.filter(raceentry__race=pk)
    bets_total_amount = Bet.objects.filter(raceentry__race=pk).aggregate(Sum('amount'))['amount__sum']
    # Bets with winning horse
    bets_won = Bet.objects.filter(raceentry__race=pk, raceentry__won=True)
    bets_won_amount = Bet.objects.filter(raceentry__race=pk, raceentry__won=True).aggregate(Sum('amount'))['amount__sum']
    if bets_won:
        win_per_ticket = round(Decimal(bets_total_amount/bets_won_amount),1)
    else:
        win_per_ticket = 'No Winning Tickets!'

    if raceentrys:
        winner = RaceEntry.objects.get(race=pk, won=True)
    else:
        winner=""

    raceentry_bets = {}
    for raceentry in raceentrys:
        raceentry_bets[raceentry.id] = Bet.objects.filter(raceentry=raceentry).aggregate(Sum('amount'))['amount__sum']

    print(raceentry_bets)

    context = {'raceentrys':raceentrys, 'bets':bets, 'race':race, 'race_status':status, 'winner':winner,
                'bets_total_amount':bets_total_amount, 'raceentry_bets':raceentry_bets,
                'bets_winning':bets_won_amount, 'win_per_ticket':win_per_ticket}

    return render(request, 'races/dashboard.html', context)

@login_required
def createBet(request, pk):
    raceentry = RaceEntry.objects.get(id=pk)
    raceid = raceentry.race.id
    raceentrys = RaceEntry.objects.filter(race=raceid)
    race = Race.objects.get(id=raceid)
    bets = Bet.objects.filter(user=request.user, raceentry__race=raceid)
    user = request.user
    form = BetCreateForm(initial={'raceentry':raceentry, 'user':user, 'amount':1})
    status = race.status

    if request.method == 'POST':
        form = BetCreateForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.user = user
            form.raceentry = raceentry            
            cash = user.profile.cash
            user.profile.cash = cash - int(request.POST['amount'])
            try:
                request.user.save()
            except:
                messages.warning(request,'Insufficent funds. Please reduce the amount.')
            else:
                form.save()
                return redirect('maindashboard') 
        else:
            for error in form.errors:     
                messages.warning(request,form.errors.get(error)[0])
                
    context = {'form':form, 'betslip':raceentry, 'raceentrys':raceentrys, 'bets':bets, 'race':race, 'race_status':status}
    return render(request, 'races/dashboard.html', context) 


def deleteBet(request, pk):
    bet = Bet.objects.get(id=pk)
    raceid = bet.raceentry.race.id
    request.user.profile.cash = request.user.profile.cash + bet.amount
    request.user.save()
    bet.delete()
    return redirect('races:dashboard', raceid)
 

# class BetCreateView(LoginRequiredMixin, CreateView):
#     model = Bet
#     fields = ('raceentry', 'amount')

#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.user = self.request.user
#         self.object.save()
#         return super().form_valid(form)  

@login_required
def Leaderboard(request):
    profiles = Profile.objects.all().order_by('-cash')

    context = {'profiles':profiles}

    return render(request, 'races/leaderboard.html', context)

@login_required
def WatchRace(request, pk):
    race = Race.objects.get(pk=pk)

    context = {'race':race}

    return render(request, 'races/watchrace.html', context)

@login_required
def WatchNextRace(request):
    races = ['In Play', 'No More Bets']
    nextrace = Race.objects.filter(status__in = races).first()

    context = {'race':nextrace}

    return render(request, 'races/watchrace.html', context)

racenight/races/templates/races/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center border border-success rounded-lg">
    <div class="row">
        <div class="col text-center">
            {% if race_status == 'In Play' %}
                <h5>Race {{ race.number }} - {{ race.name }} </h5>
                <h5 class='text-center'><span class='font-weight-bold text-success'> {{ race.status }}</span></h5> 
            {% elif race_status == 'Finished' %}          
                <h5>Race {{ race.number }} - {{ race.name }} </h5>
                <h5 class='text-center'><span class='font-weight-bold text-dange'> {{ race.status }}</span></h5> 
                <a type="button" class="btn btn-sm btn-primary px-2" href="{% url 'races:watchrace' race.id %} ">Rewatch Race</a>
            {% elif race_status == 'No More Bets' %}
                <h5>Race {{ race.number }} - {{ race.name }} </h5>
                <h5 class='text-center'><span class='font-weight-bold text-warning'> {{ race.status }}</span></h5> 
                 <a type="button" class="btn btn-sm btn-warning px-2" href="{% url 'races:watchrace' race.id %} ">Watch Race</a>
            {% else %}
                <h5>Race {{ race.number }} - {{ race.name }} </h5>
                <h5 class='text-center'><span class='font-weight-bold text-primary'> {{ race.status }}</span></h5> 
            {% endif %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}

        </div>      
    </div>
    <div class="row">
        <div class="col-md-6">
            {% if race_status == 'In Play' %}
                {% include 'races/dashboard_bet_slip.html' %}
                <br>
            {% endif %}
            {% if race_status == 'No More Bets' %}
                <br>
                {% include 'races/dashboard_mybets.html' %}  
            {% elif race_status == 'Finished' %}
                <br>
                {% include 'races/dashboard_mybets.html' %}
            {% elif race_status == 'In Play' %}
                {% include 'races/dashboard_mybets.html' %}      
            {% endif %}
            <br>
        </div>
        <div class="col-md-6 ">
            {% if race_status == 'Finished' %}
            {% include 'races/dashboard_race_results.html' %}
            <br>
            {% else %}
            {% include 'races/dashboard_race_card.html' %}
            {% endif %}
            <br>
        </div> 
    </div>
    <br>
</div>

{% endblock %}

racenight/races/templates/races/dashboard_bet_slip.html
<div class="text-center border border-success rounded-lg">
<h5>Betting Slip</h5>
{% if form %}
<h5><em>{{ form.raceentry }} {{ betslip.horse }}</em> </h5>
<form method="POST">
    {% csrf_token %}
    <h5>Stake <i class="ri-coupon-line"></i>{{ form.amount }}</h5>
    <p>{{ form.raceentry }}</p>
    <p>{{ form.user }}</p>
    <input type="submit" class = 'btn btn-success' value="Confirm">
    <a class = 'btn btn-danger' href="{% url 'races:dashboard' race.id %} ">Cancel</a>
</form>
{% else %}
<p>Select a horse from the race card to place a bet</p>  
{% endif %}
</div>

racenight/races/templates/races/dashboard_mybets.html
<div class="text-center border border-success rounded-lg">

<h5>My Bets</h5> 
{% if bets %}
<table class="table table-condensed table-striped table-sm">
    <thead>
        <tr>
            <th>No.</th>
            <th>Horse</th>
            <th>Stake</th>
            {% if race_status == 'Finished' %}
            <th>Pay Out</th>
            {% elif race_status == 'In Play' %}
            <th colspan="1"></th>
            {% else %}
            <th colspan="1"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for bet in bets %}
        {% if race_status == 'Finished' %}
            {% if bet.raceentry == winner %}
            <tr class = 'table-success'>
            {% else %}
            <tr>
            {% endif %}
        {% endif %}
            <td>{{ bet.raceentry.number }}</td>
            <td>{{ bet.raceentry.horse.name }}</td>
            <td>{{ bet.amount }}</td>
            {% if race_status == 'In Play' %}
            <td><a class='btn btn-danger btn-sm' href="{% url 'races:bet-delete' pk=bet.pk %}">Delete</td>
            {% elif race_status == 'Finished' %}
            <td>{{ bet.winnings }}</td>
            {% else %}
            <td></td>
            {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>You have no bets placed on this race.</p>
{% endif %} 
</div>

racenight/races/templates/races/dashboard_race_card.html
<div class="text-center border border-success rounded-lg">
<h5>Race Card {{ race.number }}</h1> 
    <table class="table table-condensed table-striped table-sm">
    <thead>
        <tr>
            <th>No.</th>
            <th>Horse</th>
            {% if race_status == 'In Play' %}
            <th>Select</th>
            {% else %}
            <th>
            {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for entry in raceentrys %}
        {% if race_status == 'Finished' %}
            {% if entry == winner %}
            <tr class = 'table-success'>
            {% else %}
            <tr>
            {% endif %}
        {% endif %}
            <td>{{ entry.number }}</td>
            <td>{{ entry.horse.name }}</td>
            {% if race_status == 'In Play' %}
                <td><a class='btn btn-outline-success btn-sm' href="{% url 'races:bet-create' entry.id %}">Place Bet</td>
            {% elif race_status == 'Finished' %}
                    {% if entry == winner %}
                    <td>WINNER</td> 
                    {% else %}
                    <td></td>
                    {% endif %}
            {% else %}
            <td></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

racenight/races/templates/races/dashboard_race_results.html
<div class="text-center border border-success rounded-lg">
<h5>Race Results & Betting</h5> 
<p>Winner:<span class='text-success font-weight-bold'> {{ winner.horse }}</span> </p>
<p>Pay Out per winning ticket: {{ win_per_ticket }} </p>  
<p>Total tickets bet: {{ bets_total_amount }}</p>
<p>Winning tickets: {{ bets_winning }}</p>
<table class="table table-condensed table-striped table-sm">
    <thead>
        <tr>
            <th>No.</th>
            <th>Horse</th>
            <th>Tickets</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in raceentrys %}
            {% if entry == winner %}
            <tr class = 'table-success'>
            {% else %}
            <tr>
            {% endif %}
            {% if entry == winner %}
            <td><i class='bx bx-trophy' ></i>{{ entry.number }}</td>
            {% else %}
            <td>{{ entry.number }}</td>
            {% endif %}
            <td>{{ entry.horse.name }}</td>
            {% for key, value in raceentry_bets.items %}
                {% if key == entry.id %}
                <td>{{ value }}</td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

 

racenight/races/templates/races/leaderboard.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>User</th>
                <th>Tickets</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in profiles %}
            <tr>
                <td>{{ profile.user }}</td>
                <td>{{ profile.cash }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

racenight/races/templates/races/watchrace.html
{% extends "base.html" %}

{% block content %}
<div class="embed-responsive embed-responsive-16by9">
{% if race %}
<iframe class="embed-responsive-item" src={{ race.srcyoutube }} 
        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> 
<br>
<h5 class='text-center'><span>Race {{ race.number }} - {{ race.name }} </span></h5> 
<div class='text-center'>
    <a href = {{ race.srcyoutube }}> Click here to open directly in YouTube</a>    
</div>
{% else %}
<h5 class='text-center text-success '>No more races :-(</h5>
{% endif %}
{% endblock %}