racenight/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

racenight/racenight/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="frontpage"),
    path('admin/', admin.site.urls),
    path('home/', views.home, name="home"),
    path('myaccount/', views.maindashboard, name="maindashboard"),
    path('bethistory/', views.betHistory, name="bethistory"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('races/', include("races.urls", namespace="races")),
]

racenight/races/urls.py
from django.urls import path
from . import views

app_name = 'races'

urlpatterns = [
    path('dashboard/<int:pk>',views.dashboard, name='dashboard'),
    path('bet/create/<int:pk>', views.createBet, name="bet-create"),  
    path('bet/delete/<int:pk>/',views.deleteBet, name='bet-delete'),   
    path('leaderboard/',views.Leaderboard, name='leaderboard'),
    path('watchrace/<int:pk>/',views.WatchRace, name='watchrace'), 
    path('nextrace',views.WatchNextRace, name='watchnextrace'),       
]

racenight/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Race Night</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/fonts/icofont.min.css" rel="stylesheet">
  <link href="/static/css/assets/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/css/assets/remixicon/remixicon.css" rel="stylesheet">
  

  <!-- Template Main CSS File -->
  <link href="/static/css/style.css" rel="stylesheet">
  <link href="/static/css/racenight.css" rel="stylesheet">
  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-xl-9 d-flex align-items-center justify-content-between">
          {% if user.is_authenticated %}
          <h1 class="logo"><a href="{% url 'frontpage' %}">Race Night </a>
          <a href="{% url 'maindashboard' %}">
            <span class='text-white' style='font-size:14px'><i class='bx bxs-user'></i>{{ user }}
            <span class='text-success' style='font-size:14px'><i class="ri-coupon-line"></i> {{ user.profile.cash }}</span>
          </span>
          </a>
          </h1>
          <nav class="nav-menu d-none d-lg-block">
            <ul>
              {% if user.is_superuser %}
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
              {% endif %}
              <li><a href="{%url 'frontpage' %}">Home</a></li>
              <li><a class="nav-link" href="{% url 'maindashboard' %}">Dashboard</a></li>
              <li><a class="nav-link" href="{% url 'bethistory' %}">Bet History</a></li>
              <li class="drop-down"><a href="">Races</a>
                <ul>
                  <li><a href="{% url 'races:dashboard' race_one %}">Race 1</a></li>
                  <li><a href="{% url 'races:dashboard' race_two %}">Race 2</a></li>
                  <li><a href="{% url 'races:dashboard' race_three %}">Race 3</a></li>
                  <li><a href="{% url 'races:dashboard' race_four %}">Race 4</a></li>
                  <li><a href="{% url 'races:dashboard' race_five %}">Race 5</a></li>
                </ul>
              </li>
              <li><a class="nav-link text-warning" href="{% url 'races:watchnextrace'%}">Watch Next Race</a></li>
              <li><a href="{% url 'races:leaderboard' %}">Leaderboard</a></li>
              <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </nav><!-- .nav-menu -->
          {% else %}
          <h1 class="logo"><a href="{%url 'frontpage' %}">Race Night</a></h1>
          <nav class="nav-menu d-none d-lg-block">
          <ul>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          </ul>
          </nav><!-- .nav-menu -->                    
          {% endif %}
        </div>
      </div>
    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Services Section ======= -->
    <section id="services" class="dashboard">
      <div class="container">
        {% block content %}

        {% endblock %}
      </div>
    </section><!-- End Services Section -->

  </main><!-- End #main -->

   <!-- ======= Footer ======= -->
   <footer id="footer">
    <div class="container">
      <h3>Race Night</h3>
      <div class="social-links">
        <a href="https://twitter.com/MartLivingstone" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="https://www.facebook.com/martin.livingstone.5011/" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="https://www.linkedin.com/in/martinlivingstone/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="credits">
        Martin Livingstone</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <!-- <div id="preloader"></div> -->
  <!-- <a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a> -->

  <!--  JS Files -->
  <script src="/static/js/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/static/js/assets/js/main.js"></script>
  <script src="/static/js/myscript.js"> </script>

</body>

</html>

racenight/templates/bet_history.html
{% extends "base.html" %}
{% block content %}

    {% for race in races %}
    <div class="text-center border border-success rounded-lg">
    <h5>Race:{{ race.number}} {{ race.name }}</h5> 
    {% if race.status == 'Finished' %}
    <p class='text-danger'> {{ race.status }}</p>
    {% elif race.status == 'In Play' %}
    <p class='text-success'> {{ race.status }}</p>
    {% elif race.status == 'No More Bets' %}
    <p class='text-warning'> {{ race.status }}</p>
    {% else %}
    <p class='text-primary'> {{ race.status }}</p>
    {% endif %}

    <table class="table table-condensed table-striped table-sm ">
        <thead>
            <tr>
                <th>No.</th>
                <th>Horse</th>
                <th>Stake<i class="ri-coupon-line"></i></th>
                {% if race.status == 'Finished' %}
                <th>Pay Out<i class="ri-coupon-line"></i></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
                {% for bet in bets %}
                    {% if bet.raceentry.race.id == race.id %}
                    <tr>
                        <td>{{ bet.raceentry.number }}</td>
                        <td>{{ bet.raceentry.horse.name }}</td>
                        <td>{{ bet.amount }}</td>
                        {% if race.status == 'Finished' %}
                        <td>{{ bet.winnings}}</td>
                        {% endif %}
                    </tr>
                    {% endif %}
                {% endfor %}
        </tbody>
    </table>
    </div>
    <br>
    {% endfor %}
   



{% endblock %}

racenight/templates/home.html
{% extends "base.html" %}
{% block content %}

 
    <!-- ======= Pricing Section ======= -->
    <section id="about" class="pricing">
        <div class="container">
            <div class="section-title">
                <h2>Welcome {{ user }}!</h2>
            </div>
          
          <div class="row">
  
            <div class="col-lg-4 col-md-6">
              <div class="box">
                <h3>Place your bets from your dashboard:</h3>
                <a href="{% url 'maindashboard' %}" class="btn-buy">My Dashboard</a>
              </div>
            </div>
            
            <div class="col-lg-4 col-md-6">
                <div class="box">
                  <h3>After you've placed your bets watch the race as it's streamed 'live' to all players:</h3>
                  <a href="{% url 'races:watchnextrace'%}" class="btn-buy">Watch Next Race</a>
                </div>
              </div>
              
              <div class="col-lg-4 col-md-6">
                <div class="box">
                  <h3>See how the other players are doing:</h3>
                  <a href="{% url 'races:leaderboard' %}" class="btn-buy">Leaderboard</a>
                </div>
              </div>
  
          </div>
  
        </div>
      </section><!-- End Pricing Section -->
      <br>
 
      <!-- ======= About Us Section ======= -->
      <section id="about" class="about">
        <div class="container">
          <div class="section-title">
            <h2>How to play</h2>
            <p>Pick your horse, place your bets and watch the race!</p>
          </div>
  
          <div class="row content">
            <div class="col-lg-12">
              <ul>
                Rules & Procedures:
              </ul>
              <ul>         
                <li> Tickets are used to place bets</li>
                <li> Each ticket is worth 25p</li>  
                <li> There will be five races, each with eight horses</li>
                <li> First race starts at approximately 20:15, then every 15mins thereafter</li>
                <li> You can bet on as many horses as you like provided you have enough tickets</li>
                <li> There is a two minute countdown before each race begins</li>
                <li> Betting will close approximately 1 minute before the race starts</li>
                <li> Races are streamed 'live' via YouTube</li>
                <li> After the race is over, the payouts are calculated</li>
                <li> Payout per winning ticket is the number of tickets bet on the race (the pot) divided by the number of winning tickets</li>
                <li> If you've picked the winner then your account is automatically updated with your payout</li>
                <li> Details of the amount bet on each horse for each race will be available to view after the race is over</li>
                <li> If there are no winning tickets for a race, then the pot is rolled over into the next race </li>
                <li> After the last race is over your tickets will be converted back into cash and you'll receive your payout from your Race Night rep :-)</li>
                <li> Remember it's just for fun!</li>
              </ul>
            </div>
          </div>
  
        </div>
      </section><!-- End About Us Section -->    



{% endblock %}

racenight/templates/landing.html
<link rel="stylesheet" href="/static/css/landing.css">
{% extends "base.html" %}
{% load static %}
{% block content %}

<div id="stage">
  <div id="stage-caption">
      <h1 class="display-1">Race Night!</h1>
      <a href="{% url 'accounts:login' %}" class="btn btn-lg btn-success" >Login</a>
      <a href="{% url 'accounts:signup' %}" class="btn btn-lg btn-success">Sign up now</a>
  </div>
</div>

{% endblock %}

racenight/templates/maindashboard.html
{% extends "base.html" %}
{% block content %}

<div class="container text-center ">

    <h5>My Dashboard<span class='text-success'>  Tickets <i class="ri-coupon-line"></i>{{ user.profile.cash }}</span></h5>
    
          <!-- NO MORE BETS -->
          {% for race in races %}
          {% if race.status == 'No More Bets' %}
            <div class="col border border-success rounded-lg">
              <h5>Race {{ race.number }} - {{ race.name }} </h5>
              <h5 class='text-center'><span class='font-weight-bold text-warning'> {{ race.status }}</span></h5> 
            <div class="text-center">
              <a type="button" class="btn btn-sm btn-success px-2" href="{% url 'races:dashboard' race.id %} ">Details</a>
              <a type="button" class="btn btn-sm btn-warning px-2" href="{% url 'races:watchrace' race.id %} ">Watch Race</a>
            </div>
            <br>
            <h6 class="text-center">My Bets</h6>
            <table class="table table-condensed table-striped table-sm">
              <thead>
                  <tr>
                    <th>No.</th>
                    <th>Horse</th>
                    <th>Stake<i class="ri-coupon-line"></i></th>
                  </tr>
              </thead>
              <tbody>
                  {% for bet in bets %}
                    {% if bet %}
                      <tr>
                      {% if bet.raceentry.race.id == race.id %}
                        <td>{{ bet.raceentry.number }}</td>
                        <td>{{ bet.raceentry.horse.name }}</td>
                        <td>{{ bet.amount }}</td>
                      {% endif %}
                    </tr>
                    {% else %}
                    No bets placed
                    {% endif %}
                  {% endfor %}
              </tbody>
            </table>
            </div>
            <br>
            {% endif %}
          {% endfor %}
          
    <!-- IN PLAY -->
    {% for race in races %}
    {% if race.status == 'In Play' %}
      <div class="col border border-success rounded-lg">
        <h5>Race {{ race.number }} - {{ race.name }} </h5>
        <h5 class='text-center'><span class='font-weight-bold text-success'> {{ race.status }}</span></h5> 
      <div class="text-center">
        <a type="button" class="btn btn-sm btn-success px-2" href="{% url 'races:dashboard' race.id %} ">Place Bets</a>
      </div>
      <h6 class="text-center">My Bets</h6>
      <table class="table table-condensed table-striped table-sm">
        <thead>
          <tr>
            <th>No.</th>
            <th>Horse</th>
            <th>Stake<i class="ri-coupon-line"></i></th>
          </tr>
        </thead>
        <tbody>
        {% for bet in bets %}
            <tr>
            {% if bet.raceentry.race.id == race.id %}
              <td>{{ bet.raceentry.number }}</td>
              <td>{{ bet.raceentry.horse.name }}</td>
              <td>{{ bet.amount }}</td>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
      <br>
     {% endif %}
    {% endfor %} 

      <!-- FINISHED -->
      {% for race in races %}
      {% if race.status == 'Finished' %}
        <div class="col border border-success rounded-lg">
          <h5>Race {{ race.number }} - {{ race.name }} </h5>
          <h5 class='text-center'><span class='font-weight-bold text-danger'> {{ race.status }}</span></h5> 
        <div class="text-center">
          <a type="button" class="btn btn-sm btn-success px-2" href="{% url 'races:dashboard' race.id %} ">Details</a>
          <a type="button" class="btn btn-sm btn-primary px-2" href="{% url 'races:watchrace' race.id %} ">Rewatch Race</a>
        </div>
        <h6 class="text-center">My Bets</h6>
        <table class="table table-condensed table-striped table-sm">
          <thead>
              <tr>
                <th>No.</th>
                <th>Horse</th>
                <th>Stake</th>
                <th>Pay Out<i class="ri-coupon-line"></i></th>
              </tr>
          </thead> 
          <tbody>
              {% for bet in bets %}
              {% if bet.raceentry in winners %}
                <tr class = 'table-success'>
              {% else %}
                <tr>
              {% endif %}
                {% if bet.raceentry.race.id == race.id %}
                  <td>{{ bet.raceentry.number }}</td>
                  <td>{{ bet.raceentry.horse.name }}</td>
                  <td>{{ bet.amount }}</td>
                  <td>{{ bet.winnings }}</td>
                {% endif %}
              </tr>
              {% endfor %}
          </tbody>
        </table>
        </div>
        <br>
      {% endif %}
    {% endfor %}   

    <!-- UPCOMING -->
    {% for race in races %}
    {% if race.status == 'Upcoming' %}
      <div class="col border border-success rounded-lg">
        <h5>Race {{ race.number }} - {{ race.name }} </h5>
        <h5 class='text-center'><span class='font-weight-bold text-primary'> {{ race.status }}</span></h5> 
      <h6 class="text-center">Race Card</h6>
      <table class="table table-condensed table-striped table-sm">
        <thead>
            <tr>
                <th>No.</th>
                <th>Horse</th>
            </tr>
        </thead>
        <tbody>
            {% for raceentry in raceentrys %}
                <tr>
                {% if raceentry.race.id == race.id %}
                  <td>{{ raceentry.number }}</td>
                  <td>{{ raceentry.horse.name }}</td>
                {% endif %}
              </tr>
            {% endfor %}
        </tbody>
      </table>
      </div>
    <br>
    {% endif %}
    {% endfor %}

   

</div>




{% endblock %}